version: "3.9"
services:
  mysql-service:
    image: mysql:8.0
    container_name: mysql-service
    hostname: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "traccar"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 5

  traccar:
    image: traccar/traccar:6.2
    container_name: traccar
    hostname: traccar
    volumes:
      - traccar-data:/opt/traccar/logs
    environment:
      CONFIG_USE_ENVIRONMENT_VARIABLES: "true"
      DATABASE_DRIVER: "com.mysql.cj.jdbc.Driver"
      DATABASE_URL: "jdbc:mysql://mysql-service/traccar?zeroDateTimeBehavior=round&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&sessionVariables=sql_mode=''"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"

      # ONLY FOR DEVELOPMENT
      LOGGER_CONSOLE: "true"
    ports:
      - "8082:8082"
      - "5000-5150:5000-5150"
      - "5000-5150:5000-5150/udp"
    depends_on:
      mysql-service:
        condition: service_healthy
    restart: unless-stopped

volumes:
  traccar-data:
  mysql-data:
